/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Circle cir1 = new Circle(1);
        cir1.calculateArea();
        cir1.calculatePerimeter();

        Rectangle rectangle = new Rectangle(2, 2);
        rectangle.calculateArea();
        rectangle.calculatePerimeter();

        Triangle triangle = new Triangle(2,2,2,2);
        triangle.calculateArea();
        triangle.calculatePerimeter();
    }
}
