/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Circle cir1 = new Circle(1);
        double areaOfCir1 = cir1.calculateArea();
        System.out.printf("Area of circle: %.3f%n", areaOfCir1);
        double perimeterOfCir1 = cir1.calculatePerimeter();
        System.out.printf("Perimeter of circle: %.3f%n", perimeterOfCir1);
    }
}
