/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class App {

    public static void main(String[] args) {
        Circle circle = new Circle(3);
        circle.calculateArea();
        circle.calculatePerimeter();
        circle.read();
        circle.save();
//        Rectangle rectangle = new Rectangle(2, 2);
//        rectangle.calculateArea();
//        rectangle.calculatePerimeter();
//
//        Triangle triangle = new Triangle(2, 2, 2, 2);
//        triangle.calculateArea();
//        triangle.calculatePerimeter();
    }
}
